# Problem Statement :
## Using the independent features predict horsepower of the models 

In [2]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [3]:
df=pd.read_csv(r'C:\Users\APOORVA\Downloads\archive\auto-mpg.csv')

#### Basic EDA

In [4]:
df

mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0        130    3504          12.0   
1    15.0          8         350.0        165    3693          11.5   
2    18.0          8         318.0        150    3436          11.0   
3    16.0          8         304.0        150    3433          12.0   
4    17.0          8         302.0        140    3449          10.5   
..    ...        ...           ...        ...     ...           ...   
393  27.0          4         140.0         86    2790          15.6   
394  44.0          4          97.0         52    2130          24.6   
395  32.0          4         135.0         84    2295          11.6   
396  28.0          4         120.0         79    2625          18.6   
397  31.0          4         119.0         82    2720          19.4   

     model year  origin                   car name  
0            70       1  chevrolet chevelle malibu  
1            70       1          buick skylark 320  
2            70       1         plymouth satellite  
3            70       1              amc rebel sst  
4            70       1                ford torino  
..          ...     ...                        ...  
393          82       1            ford mustang gl  
394          82       2                  vw pickup  
395          82       1              dodge rampage  
396          82       1                ford ranger  
397          82       1                 chevy s-10  

[398 rows x 9 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object 
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64  
 7   origin        398 non-null    int64  
 8   car name      398 non-null    object 
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB


In [6]:
df.tail()

mpg  cylinders  displacement horsepower  weight  acceleration  \
393  27.0          4         140.0         86    2790          15.6   
394  44.0          4          97.0         52    2130          24.6   
395  32.0          4         135.0         84    2295          11.6   
396  28.0          4         120.0         79    2625          18.6   
397  31.0          4         119.0         82    2720          19.4   

     model year  origin         car name  
393          82       1  ford mustang gl  
394          82       2        vw pickup  
395          82       1    dodge rampage  
396          82       1      ford ranger  
397          82       1       chevy s-10

In [7]:
df.head()

mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   
2  18.0          8         318.0        150    3436          11.0          70   
3  16.0          8         304.0        150    3433          12.0          70   
4  17.0          8         302.0        140    3449          10.5          70   

   origin                   car name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino

In [8]:
corr=df.corr()

In [9]:
corr

mpg  cylinders  displacement    weight  acceleration  \
mpg           1.000000  -0.775396     -0.804203 -0.831741      0.420289   
cylinders    -0.775396   1.000000      0.950721  0.896017     -0.505419   
displacement -0.804203   0.950721      1.000000  0.932824     -0.543684   
weight       -0.831741   0.896017      0.932824  1.000000     -0.417457   
acceleration  0.420289  -0.505419     -0.543684 -0.417457      1.000000   
model year    0.579267  -0.348746     -0.370164 -0.306564      0.288137   
origin        0.563450  -0.562543     -0.609409 -0.581024      0.205873   

              model year    origin  
mpg             0.579267  0.563450  
cylinders      -0.348746 -0.562543  
displacement   -0.370164 -0.609409  
weight         -0.306564 -0.581024  
acceleration    0.288137  0.205873  
model year      1.000000  0.180662  
origin          0.180662  1.000000

In [10]:
pd.set_option('display.max_row',None)

In [11]:
pd.DataFrame(df['horsepower'].value_counts())

horsepower
150          22
90           20
88           19
110          18
100          17
95           14
75           14
105          12
70           12
67           12
65           10
85            9
97            9
80            7
140           7
145           7
?             6
84            6
78            6
72            6
92            6
68            6
130           5
86            5
170           5
71            5
60            5
180           5
115           5
175           5
52            4
120           4
83            4
76            4
165           4
190           3
112           3
215           3
225           3
63            3
74            3
125           3
96            3
48            3
69            3
81            2
46            2
53            2
87            2
160           2
198           2
139           2
79            2
155           2
98            2
129           2
153           2
58            2
62            2
193           1
210           1
220           1
208           1
135           1
49            1
108           1
103           1
148           1
94            1
107           1
230           1
142           1
82            1
91            1
167           1
122           1
200           1
137           1
93            1
77            1
102           1
54            1
89            1
138           1
61            1
158           1
132           1
133           1
152           1
113           1
64            1
149           1
116           1
66            1

In [12]:
df[['horsepower']]

horsepower
0          130
1          165
2          150
3          150
4          140
5          198
6          220
7          215
8          225
9          190
10         170
11         160
12         150
13         225
14          95
15          95
16          97
17          85
18          88
19          46
20          87
21          90
22          95
23         113
24          90
25         215
26         200
27         210
28         193
29          88
30          90
31          95
32           ?
33         100
34         105
35         100
36          88
37         100
38         165
39         175
40         153
41         150
42         180
43         170
44         175
45         110
46          72
47         100
48          88
49          86
50          90
51          70
52          76
53          65
54          69
55          60
56          70
57          95
58          80
59          54
60          90
61          86
62         165
63         175
64         150
65         153
66         150
67         208
68         155
69         160
70         190
71          97
72         150
73         130
74         140
75         150
76         112
77          76
78          87
79          69
80          86
81          92
82          97
83          80
84          88
85         175
86         150
87         145
88         137
89         150
90         198
91         150
92         158
93         150
94         215
95         225
96         175
97         105
98         100
99         100
100         88
101         95
102         46
103        150
104        167
105        170
106        180
107        100
108         88
109         72
110         94
111         90
112         85
113        107
114         90
115        145
116        230
117         49
118         75
119         91
120        112
121        150
122        110
123        122
124        180
125         95
126          ?
127        100
128        100
129         67
130         80
131         65
132         75
133        100
134        110
135        105
136        140
137        150
138        150
139        140
140        150
141         83
142         67
143         78
144         52
145         61
146         75
147         75
148         75
149         97
150         93
151         67
152         95
153        105
154         72
155         72
156        170
157        145
158        150
159        148
160        110
161        105
162        110
163         95
164        110
165        110
166        129
167         75
168         83
169        100
170         78
171         96
172         71
173         97
174         97
175         70
176         90
177         95
178         88
179         98
180        115
181         53
182         86
183         81
184         92
185         79
186         83
187        140
188        150
189        120
190        152
191        100
192        105
193         81
194         90
195         52
196         60
197         70
198         53
199        100
200         78
201        110
202         95
203         71
204         70
205         75
206         72
207        102
208        150
209         88
210        108
211        120
212        180
213        145
214        130
215        150
216         68
217         80
218         58
219         96
220         70
221        145
222        110
223        145
224        130
225        110
226        105
227        100
228         98
229        180
230        170
231        190
232        149
233         78
234         88
235         75
236         89
237         63
238         83
239         67
240         78
241         97
242        110
243        110
244         48
245         66
246         52
247         70
248         60
249        110
250        140
251        139
252        105
253         95
254         85
255         88
256        100
257         90
258        105
259         85
260        110
261        120
262        145
263        165
264        139
265        140

In [13]:
df['horsepower']=df['horsepower'].replace('?',np.nan).astype('float')

In [14]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower      float64
weight            int64
acceleration    float64
model year        int64
origin            int64
car name         object
dtype: object

In [15]:
df['horsepower'].median()

93.5

In [16]:
df['horsepower'].fillna(df['horsepower'].median(),inplace=True)

In [17]:
df.isna().apply(pd.value_counts).T

False
mpg             398
cylinders       398
displacement    398
horsepower      398
weight          398
acceleration    398
model year      398
origin          398
car name        398

In [18]:
corr=df.corr()

In [19]:
corr

mpg  cylinders  displacement  horsepower    weight  \
mpg           1.000000  -0.775396     -0.804203   -0.773453 -0.831741   
cylinders    -0.775396   1.000000      0.950721    0.841284  0.896017   
displacement -0.804203   0.950721      1.000000    0.895778  0.932824   
horsepower   -0.773453   0.841284      0.895778    1.000000  0.862442   
weight       -0.831741   0.896017      0.932824    0.862442  1.000000   
acceleration  0.420289  -0.505419     -0.543684   -0.686590 -0.417457   
model year    0.579267  -0.348746     -0.370164   -0.413733 -0.306564   
origin        0.563450  -0.562543     -0.609409   -0.452096 -0.581024   

              acceleration  model year    origin  
mpg               0.420289    0.579267  0.563450  
cylinders        -0.505419   -0.348746 -0.562543  
displacement     -0.543684   -0.370164 -0.609409  
horsepower       -0.686590   -0.413733 -0.452096  
weight           -0.417457   -0.306564 -0.581024  
acceleration      1.000000    0.288137  0.205873  
model year        0.288137    1.000000  0.180662  
origin            0.205873    0.180662  1.000000

In [20]:
corr[['horsepower']]

horsepower
mpg            -0.773453
cylinders       0.841284
displacement    0.895778
horsepower      1.000000
weight          0.862442
acceleration   -0.686590
model year     -0.413733
origin         -0.452096

##### Define the independent variable

In [21]:
X=df.drop(['mpg','acceleration','model year','origin','car name'],axis=1)

##### Define the Dependent variable

In [22]:
y=df[['horsepower']]

In [23]:
##### Importing train test split

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1)

In [26]:
X_train.shape

(278, 4)

In [27]:
X_test.shape

(120, 4)

In [28]:
y_train.shape

(278, 1)

In [29]:
y_test.shape

(120, 1)

In [30]:
from sklearn.linear_model import LinearRegression

In [31]:
model=LinearRegression()

In [32]:
model.fit(X_train,y_train)

LinearRegression()

In [33]:
y_pred=model.predict(X_test)

In [34]:
y_pred

array([[ 97. ],
       [ 80. ],
       [140. ],
       [103. ],
       [ 90. ],
       [149. ],
       [ 49. ],
       [ 62. ],
       [120. ],
       [180. ],
       [ 84. ],
       [110. ],
       [120. ],
       [110. ],
       [ 58. ],
       [ 98. ],
       [198. ],
       [ 95. ],
       [198. ],
       [ 65. ],
       [ 97. ],
       [ 78. ],
       [ 85. ],
       [ 88. ],
       [ 90. ],
       [ 46. ],
       [ 75. ],
       [ 52. ],
       [140. ],
       [ 92. ],
       [110. ],
       [220. ],
       [ 87. ],
       [ 95. ],
       [ 88. ],
       [175. ],
       [ 79. ],
       [225. ],
       [ 84. ],
       [ 75. ],
       [ 80. ],
       [ 89. ],
       [129. ],
       [ 74. ],
       [115. ],
       [105. ],
       [ 98. ],
       [165. ],
       [ 75. ],
       [110. ],
       [ 88. ],
       [105. ],
       [145. ],
       [158. ],
       [ 83. ],
       [ 92. ],
       [208. ],
       [153. ],
       [ 70. ],
       [ 67. ],
       [ 74. ],
       [ 67. ],
       [

In [35]:
 y_test=y_test.values

In [36]:
model.coef_

array([[-3.07981445e-15, -2.38496268e-16,  1.00000000e+00,
        -6.67722452e-18]])

In [37]:
model.intercept_

array([9.9475983e-14])

In [38]:
df_comp=pd.DataFrame({'Actual HP': y_test.flatten(),'Predicted HP': y_pred.flatten()})
df_comp.head()

Actual HP  Predicted HP
0       97.0          97.0
1       80.0          80.0
2      140.0         140.0
3      103.0         103.0
4       90.0          90.0

In [39]:
model.score(X_test,y_test)*100

100.0